### ISSUE TITLE
Video / User Manual 

### ISSUE THREAD

**Issue by GoodbyeKittyy** [FrancescoDiSalesDEV/SimpleVirusWriting#1]
Hi there,

Is there any video, or user manual that I can refer to run this example? I am finding related projects to showcase in a demonstration :)

**Comment by FrancescoDiSalesGithub** [comment]
There are makefiles for each demonstration. Just run make -f makefile

**Comment by FrancescoDiSalesGithub** [comment]
Anyway, yes, the readme should be updated
